@startuml

class "Document Entry" as d {
    availabilityStatus : code
    [[ValueSet-IHEXDSclassCode.html class]] : code
    [[ValueSet-IHEXDStypeCode.html type]] : code
    [[ValueSet-IHEXDSconfidentialityCode.html confidentiality]]: code
    [[ValueSet-IHEXDSeventCodeList.html event]] : code[]
    [[ValueSet-IHEXDSlanguageCode.html language]]: code
    [[ValueSet-IHEXDSformatCodeDE.html format]]: code
    [[ValueSet-IHEXDSpracticeSettingCode.html practiceSetting]]: code
    [[ValueSet-IHEXDShealthcareFacilityTypeCode.html healthcareFacilityTypeCode]]: code
}

class "Author" as a {
    [[ValueSet-IHEXDSauthorRole.html role]]: code
    [[ValueSet-IHEXDSauthorSpeciality.html specialty]]: code
}

class "Folder" as f {
    availabilityStatus : code
    [[ValueSet-IHEXDScodeList.html code]]: code[]
}

d "1" *-right- "0..*" a
f "0..*" -- "1" d

@enduml