@startuml

class "Document Entry" as d {
    availabilityStatus : code
    [[ValueSet-IHEXDSclassCode.html class]] : code
    [[ValueSet-IHEXDStypeCode.html type]] : code
    [[ValueSet-IHEXDSconfidentialityCode.html confidentiality]]: code
    [[ValueSet-IHEXDSeventCodeList.html event]] : code[]
    [[ValueSet-IHEXDSlanguageCode.html language]]: code
    [[ValueSet-IHEXDSformatCode.html format]]: code
    [[ValueSet-IHEXDSpracticeSettingCode.html practiceSetting]]: code
    [[ValueSet-IHEXDShealthcareFacilityType.html healthcareFacilityType]]: code
}

class "Author" as a {
    [[ValueSet-IHEXDSauthorRole.html authorRole]]: code
    [[ValueSet-IHEXDSauthorSpecialty.html authorSpecialty]]: code
}

class "Folder" as f {
    availabilityStatus : code
    [[ValueSet-IHEXDSfolderCodeList.html code]]: code[]
}

d "1" *-right- "0..*" a
f --> d

@enduml