@startuml

class "SubmissionSet" as s {
    availability : code
    [[ValueSet-IHEXDScontentTypeCode.html contentType]] : code
}

class "Author" as a {
    [[ValueSet-IHEXDSauthorRole.html authorRole]]: code
    [[ValueSet-IHEXDSauthorSpeciality.html authorSpecialty]]: code
}

class "[[document.html Document Entry]]" as de {

}

s "1..*" -- "0..*" de
s "1" *-right- "1..*" a

@enduml